---
- name: Create a resource group
  azure_rm_resourcegroup:
    name: "{{ azure_resource_group_name }}"
    location: "{{ azure_location }}"
    tags:
      environment: "{{ env | default('') }}"
  ignore_errors: yes

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ azure_resource_group_name }}"
    name: "{{ azure_virtual_network_name }}"
    address_prefixes: "{{ azure_virtual_network_prefixes }}"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ azure_resource_group_name }}"
    name: "{{ azure_subnet_name }}"
    address_prefix: "{{ azure_subnet_prefixes }}"
    virtual_network: "{{ azure_virtual_network_name }}"

- name: Create Network Security Group
  azure_rm_securitygroup:
    resource_group: "{{ azure_resource_group_name }}"
    name: "{{ azure_security_group_name }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
      - name: WINRM
        protocol: Tcp
        destination_port_range: 5986
        access: Allow
        priority: 1002
        direction: Inbound
      - name: RDP
        protocol: Tcp
        destination_port_range: 3389
        access: Allow
        priority: 1003
        direction: Inbound
      - name: MSSQL
        protocol: Tcp
        destination_port_range: 1433
        access: Allow
        priority: 1004
        direction: Inbound

- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ azure_resource_group_name }}"
    allocation_method: Static
    name: "ip_{{ azure_prefix }}{{ item.name }}"
  with_items: "{{ nodes }}"
  when: nodes is defined

- name: Create virtual network inteface card
  azure_rm_networkinterface:
    resource_group: "{{ azure_resource_group_name }}"
    name: "ni_{{ azure_prefix }}{{ item.name }}"
    virtual_network: "{{ azure_virtual_network_name }}"
    subnet: "{{ azure_subnet_name }}"
    public_ip_name: ip_{{ azure_prefix }}{{ item.name }}
    security_group: "{{ azure_security_group_name }}"
  with_items: "{{ nodes }}"
  when: nodes is defined

- name: Create Windows VM
  azure_rm_virtualmachine:
    resource_group: "{{ azure_resource_group_name }}"
    name: "vm-{{ azure_prefix | lower }}-{{ item.name | lower }}"
    vm_size: "{{ item.vm_size }}"
    public_ip_allocation_method: Dynamic
    managed_disk_type: Standard_LRS
    open_ports:
      - 3389
      - 1433
      - "{{ ansible_port }}"
    os_type: "{{ item.os_type }}"
    network_interfaces: ni_{{ azure_prefix }}{{ item.name }}
    admin_username: "{{ ansible_user }}"
    admin_password: "{{ ansible_password }}"
    image: "{{ item.image }}"
    remove_on_absent: all
    tags:
      name: "vm_{{ azure_prefix | lower }}{{ item.name | lower }}"
      environment: "{{ env | default('') }}"
      role: "{{ item.role }}"
      app: "{{ item.app_name }}"
      pod: "{{ item.pod_name | default('') }}"
      user: "{{ item.username | default('') }}"
  async: 7200
  poll: 0
  register: deploy
  with_items: "{{ nodes }}"
  when: nodes is defined

- name: Wait for instance creation to complete
  async_status: jid="{{ item.ansible_job_id }}"
  register: instances
  until: instances.finished
  retries: "{{ instance_wait_retry_limit }}"
  delay: 10
  with_items: "{{ deploy.results }}"

- name: pause for VMs to stabilize
  pause:
    seconds: "{{ pause_in_seconds }}"

- name: Delete VM Extension
  azure_rm_virtualmachine_extension:
    name: "ve_{{ azure_prefix }}_{{ item.0 }}"
    resource_group: "{{ azure_resource_group_name }}"
    virtual_machine_name: "{{ item.1.ansible_facts.azure_vm.name }}"
    state: absent
  with_indexed_items: "{{ instances.results }}"
  ignore_errors: yes
  when:
    - instances.results is defined
    - nodes is defined

- name: Create VM Extension
  azure_rm_virtualmachine_extension:
    name: "ve_{{ azure_prefix }}_{{ item.0 }}"
    resource_group: "{{ azure_resource_group_name }}"
    virtual_machine_name: "{{ item.1.ansible_facts.azure_vm.name }}"
    publisher: Microsoft.Compute
    virtual_machine_extension_type: CustomScriptExtension
    type_handler_version: 1.9
    #settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell.exe -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP"}'
    settings: '{"commandToExecute": "powershell.exe -ExecutionPolicy ByPass -EncodedCommand {{ winrm_enable_script }}"}'
    auto_upgrade_minor_version: true
  with_indexed_items: "{{ instances.results }}"
  when:
    - instances.results is defined
    - nodes is defined

- name: Waiting for server to come online
  wait_for:
    host: "{{ item.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    port: "{{ ansible_port }}"
    timeout: "{{ instance_wait_connection_timeout }}"
  with_items: "{{ instances.results }}"
  when:
    - instances.results is defined
    - nodes is defined







